### ISSUE TITLE
Identical CardId for the same card

### ISSUE THREAD

**Issue by StasevichVitaliy** [Mangopay/cardregistration-js-kit#48]
Hi,
I have question regards identifying cards that have already been registered. Right now for the same TEST cards(identical card number, expiry date, ccv) registerCard method return different CardIds. Is it only for test cards? If no, how to determine that card has already been registered?

**Comment by mickaelpois** [comment]
Hi @StasevichVitaliy and thanks for your question !

On our side, each registration of a card is a new card object, with a different CardId.
Why ? Because, at the moment, you can (and you have to) register the same card (ie. same card number) for each currency you want to use this ward with.

Example:
Card 1234XXXXXXXX7890 - EUR = CardID 1
Card 1234XXXXXXXX7890 - GBP = CardID 2
Card 1234XXXXXXXX7890 - EUR = CardID 3 (weird, but possible)

If you wanna find if a card has been registered, please use our Fingerprint feature: https://docs.mangopay.com/endpoints/v2.01/cards#e952_list-cards-for-a-fingerprint

Card 1 / 2 and 3 has the same Fingerprint value, even if Object ID is different.

Mickaël

**Comment by StasevichVitaliy** [comment]
@mickaelpois thanks a lot
